#数据源配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/yuta?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&serverTimezone=GMT%2B8
    username: root
    password: root
