#服务器配置
server:
  port: 8080
  servlet:
    context-path: /api
  undertow:
    # 设置IO线程数, 它主要执行非阻塞的任务,它们会负责多个连接, 默认设置每个CPU核心一个线程
    io-threads: 16
    # 阻塞任务线程池, 当执行类似servlet请求阻塞操作, undertow会从这个线程池中取得线程,它的值设置取决于系统的负载
    worker-threads: 400
    # 以下的配置会影响buffer,这些buffer会用于服务器连接的IO操作,有点类似netty的池化内存管理
    buffer-size: 1024
    # 是否分配的直接内存
    direct-buffers: true

# spring配置
spring:
  profiles:
    active: dev
  main:
    banner-mode: "off"
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  cache:
    type: redis
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 1000
    password:

# mybatis配置
mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  typeAliasesPackage: com.hy.**.entity
  global-config:
    banner: false

# log配置
logging:
  config: classpath:log/logback_${spring.profiles.active}.xml